### PR TITLE
Fix nubBy

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by garyb** [comment]
What's wrong with the original? Is it not using the provided equality function?

**Comment by jacereda** [comment]
Yes, that's it.

**Comment by paf31** [comment]
Nope:

```purescript
> nubBy (\_ _ -> true) [1,2,3,4,5]

[1]
```

More worrying:

```
> nubBy ((==) `on` (\n -> n % 2)) [1,2,3,4,5]

.psci_modules/node_modules/$PSCI/index.js:7
    return (Prelude.numNumber % n)(2);
                                  ^
TypeError: number is not a function
```

**Comment by paf31** [comment]
What is this fixing?

**Comment by jacereda** [comment]
Oops, I thought it was somehow pattern-matching on the function.

**Pull request closed without merging**
