### PR TITLE
Faster concat.

### PR DESCRIPTION
**Pull request by dikmax**
Simply calling `concat` is much faster that going through loop.

### CODE REVIEW

**Comment by garyb** [comment]
Unfortunately this version isn't "safe" - see #42

**Comment by hdgarrood** [comment]
I'm also not sure that this implementation is faster anyway, at least I don't think it was last time i checked. Did you do any benchmarks?

**Comment by dikmax** [comment]
Here's some benchmarks <https://jsperf.com/concat-vs-push100>

I'll try to think something that wouldn't cause rangeerror.

**Comment by hdgarrood** [comment]
I think benchmarks need to use a variety of array sizes to be useful, we can't see the whole picture from a test with just one input. I think it's a bit of a shame that jsperf encourages benchmarks like this, actually. I'd prefer to see a benchmark using a variety of inputs with different sizes before making a change like this.

You might find my library purescript-benchotron useful for creating a more comprehensive benchmark.

**Pull request closed without merging**
