### PR TITLE
[BREAKING] Remove filterM

### PR DESCRIPTION
**Pull request by hdgarrood**

### CODE REVIEW

**Comment by rightfold** [comment]
Why?

**Comment by hdgarrood** [comment]
Because we have `filterA` now which only needs an `Applicative`, and is significantly faster - both asymptotically and in practice.

**Comment by hdgarrood** [comment]
Oh actually I guess the perf argument doesn't really make sense because filterM is now just an alias for filterA. I think filterA should be preferred because it can be misleading to ask for a Monad when you're only using an Applicative.

**Comment by rightfold** [comment]
Maybe time to try out the shiny new `Warn` constraints?

**Comment by garyb** [comment]
That'd be breaking too :smile:

**Pull request merged**
