### PR TITLE
make `head` and `last` O(1), not O(n).

### PR DESCRIPTION
**Pull request by hdgarrood**
refs #13.

Avoid pattern matching for `head` and `last` to make them O(1).

Note that this changes behaviour slightly - `Data.Array.Unsafe.head ([] :: [Unit]) == unit`, because it now uses `unsafeIndex`. Previously it would throw "Failed pattern match".

### CODE REVIEW

**Comment by paf31** [comment]
Sorry I missed this one. Could you please merge it with master, and I can merge it back?

**Comment by hdgarrood** [comment]
Like that?

**Comment by paf31** [comment]
Yep :+1: 

Does this need rebasing, or is it just going to show up as 2 commits?

**Comment by hdgarrood** [comment]
I can merge this into my master branch locally and it just shows up as 2 commits.

**Comment by hdgarrood** [comment]
Alternatively I am happy to rebase for a nicer history.

**Comment by paf31** [comment]
Thanks!

**Comment by paf31** [comment]
Oops, now the docs are wrong :P

**Comment by paf31** [comment]
Would you mind just changing the `N`s to `1`s and I'll rerelease?

**Comment by hdgarrood** [comment]
Sure, will do

**Pull request merged**
