### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by paluh**
Backlinking to purescript/purescript#3942

### CODE REVIEW

**Comment by paluh** [comment]
Includes #176

**Comment by srghma** [comment]
related https://github.com/purescript/purescript-arrays/pull/183

**Comment by JordanMartinez** [comment]
@paluh please merge #183 into this PR

**Comment by kl0tl** [comment]
We could replace some uses of unsafeCoerce by Safe.Coerce.coerce in the implementations of Data.Array.NonEmpty.unsafeFromArray, Data.Array.NonEmpty.toArray and Data.Array.groupBy. This requires the NonEmptyArray constructor to be in scope so we should be careful not to re-export it from Data.Array.NonEmpty.

Sadly we can’t remove the last unsafeCoerce from Data.Array.unsafeFromArrayF implementation without strengthening its type with a `Coercible (f (Array a)) (f (NonEmptyArray a))` constraint, so we should probably refrain from doing it (at least until we have constraint kinds and quantified constraints so we can define `type Representational f = forall a b. Coercible a b => Coercible (f a) (f b)`).

**Comment by paluh** [comment]
@JordanMartinez I've included #183 . Do we want to include suggestions by @kl0tl here too?

**Comment by JordanMartinez** [comment]
I think we should do @kl0tl's suggestions in a separate PR. They aren't strictly needed to update this library to v0.14.0, but are welcome improvements.

**Comment by JordanMartinez** [comment]
@paluh All dependencies are now satisfied again. We're still getting an error due to the [following line](https://travis-ci.org/github/purescript/purescript-arrays/builds/739085587#L741):
```
[1/1 WarningParsingModule] src/Data/Array/ST.purs:34:30

  34  import Control.Monad.ST (ST, kind Region)

                                   ^^^^^^^^^^^

  

  Kind imports are deprecated and will be removed in a future release. Omit the 'kind' keyword instead.

```
We just need to delete the `kind` word.

**Review by JordanMartinez — APPROVED** [review]
CI now builds. I've also looked through the changes made and have verified that no unicode syntax is being used.

We'll need a second approval before we can merge. Once merged, this will unblock `purescript-transformers`.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
