### PR TITLE
Faster replicate.

### PR DESCRIPTION
**Pull request by dikmax**
Faster version of replicate. Here are benchmark results.

replicate

You can check benchmark itself here: <https://github.com/dikmax/purescript-array-benchmarks>.

### CODE REVIEW

**Comment by hdgarrood** [comment]
This looks great but sadly I don't think we can justify using this implementation due to its relative lack of support: https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/fill

What does it look like for smaller arrays, where the argument is between, say, 1 and 10000?

**Comment by dikmax** [comment]
Here are smaller arrays.

replicate 1

I can write version, which selects method depending on the presence of `fill` in arrays prototype. What do you think?

**Comment by hdgarrood** [comment]
Great! I think that should work, yeah. It would be good to have a version that only selects the method once, i.e. ideally we would only check once for `Array.prototype.fill`, not every time `replicate` is called, I think.

**Comment by dikmax** [comment]
Fixed.

**Pull request merged**
