### PR TITLE
Added the find function

### PR DESCRIPTION
**Pull request by Risto-Stevcev**

### CODE REVIEW

**Comment by garyb** [comment]
`find` is in `Foldable` :smile:

**Comment by Risto-Stevcev** [comment]
Ah! I didn't notice that. What do you think of re-exporting it from `Foldable` so that it's available in `Data.Array` also?
`purescript-foldable-traversable` is already a dependency for `purescript-arrays`

**Comment by garyb** [comment]
Yeah, that makes sense. There are probably a few other common functions we could export from there too.

/cc @paf31

**Comment by paf31** [comment]
👍

**Comment by garyb** [comment]
Oh sorry, I see you pushed another change. I ended up including the re-exports in my other PR.

**Comment by Risto-Stevcev** [comment]
Ah it's okay, I was being slow :sweat_smile:

**Pull request closed without merging**
